pipeline {
    agent any
    tools { jdk 'jdk17'; maven 'maven3' }
    stages {
        stage('Test') {
            steps { sh 'mvn --batch-mode clean verify' }
        }
        stage('Package') {
            steps { archiveArtifacts artifacts: 'bootstrap/target/*.jar', fingerprint: true }
        }
    }
}
